### ISSUE TITLE
Support traffic times from multiple routes (Directions API?)

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/arduino-google-maps-api#2]
A user on reddit requested that the API supports traffic times on multiple routes, as in there are multiple routes to get from A-> B, which one is the fastest. I think this is a worth while feature

It seems like the [Directions API](https://developers.google.com/maps/documentation/directions/intro) will support this. It does seem like the response is going to be pretty big though as it's giving step by step directions.

User is currently trying to implement but I thought it would be good to track here

**Comment by witnessmenow** [comment]
This library may help extract just the information we need

https://github.com/squix78/json-streaming-parser

Edit: Blog post from author of this library:
https://blog.squix.org/2017/01/esp8266-the-json-streaming-parser.html

**Comment by nighthawk4900** [comment]
Please excuse my informal approach to this. 

I created a duplicate of your functions that access the google distance matrix API to access the Directions API (it needed its own key, and has a slightly different GET command)

Then I used the JSon streaming parser which you linked to parse the body for the "Summary" key, and then took the value following the summary key to display on the screen as the "Route"


Added a small for loop in the code parsing telegram messages so that you can send the /origin and /destination messages without '+' signs ("Dublin, Ireland" instead of Dublin,+Ireland)

**Comment by nighthawk4900** [comment]
[Traffic notifier with Route Summary.zip](https://github.com/witnessmenow/arduino-google-maps-api/files/979616/Traffic.notifier.with.Route.Summary.zip)

**Comment by nighthawk4900** [comment]
Not sure how else to upload this code....or do a pull request...

**Comment by witnessmenow** [comment]
Hey,

No problem! I'll take a look the weekend

Thanks a lot!

**Comment by nighthawk4900** [comment]
![img_3325](https://cloud.githubusercontent.com/assets/24865902/25762290/35316e00-31ac-11e7-8bac-ece9b80adcef.JPG)

**Comment by nighthawk4900** [comment]
![img_3329](https://cloud.githubusercontent.com/assets/24865902/25762312/509c0e5c-31ac-11e7-9e2a-0094bcae4809.JPG)

**Comment by witnessmenow** [comment]
@nighthawk4900 do directions and matrix need different keys? I wouldn't have thought they did.

I'm just going to play around with it now, looks good though!

I think i might change it up so that the two different options are in different files in the library. As currently if you want to use the directionsApi you still are loading ArduinoJson library despite never using it and same the other way around with the JsonStreamer

**Comment by nighthawk4900** [comment]
@witnessmenow Yea they need different keys, and slightly different GET commands.

And thats a good point... but as it stands, actually both APIs are called, and so all the original libraries are used (the arduinojson lib for the original distance matrix api)

I am using the arduinoIDE so I wasnt exactly sure how to separate everything into different files...

**Comment by witnessmenow** [comment]
No problem! That makes it nearly a little easier to separate as they really don't share anything. I'm working on it at the moment I'll keep you posted

**Comment by witnessmenow** [comment]
@nighthawk4900 So I put up some changes on a [new branch](https://github.com/witnessmenow/arduino-google-maps-api/tree/directionsApi) (branches are just a different version of the code) that is based on your changes.

It's working anyways! Thanks a lot for all the work so far on it

There is more work to do though:

- It still no [waypoints](https://developers.google.com/maps/documentation/directions/intro#Waypoints) parameter, which you would need to compare the travel time multiple different ways.
- The "values" need to be converted to int and stored in the responseObject
- Even when we get all the data we want back we are still waiting for the timeout (your solution worked fine when there was only one data point but i'm not sure makes as much sense if there are more than 1

Unfortunately is 1:20 am for me and I have work in the morning!

**Comment by witnessmenow** [comment]
I forgot to mention there is a very simple example in the new branch too
for it, which also needs the other fields printed out

**Comment by witnessmenow** [comment]
Was making decent progress til I added waypoints in, It changes how the response comes back! If you are looking for travel time from A->B via C it responds with an array, one containing A->C and the other containing C->B 

shouldn't be too big of a deal

**Comment by witnessmenow** [comment]
What I describe above goes away if you specify the waypoint with a "via:" and traffic is only supported using the via way (I found this out after implementing a solution for the other way!

Will raise a PR to trigger a build and if it passes I will merge and make a release which should get picked up by the Arduino library manager

**Comment by witnessmenow** [comment]
@nighthawk4900 merged now, should be available on Arduino library manager soon.

Let me know how it goes if you try it out!
